### ISSUE TITLE
Set the "data" directory to the Conda prefix?

### ISSUE THREAD

**Issue by gwerbin** [conda-forge/geographiclib-cpp-feedstock#8]
### Comment:

As per the [docs](https://geographiclib.sourceforge.io/C++/doc/install.html#cmake), the `GEOGRAPHICLIB_DATA` option controls the default search and installation location for data files that can be downloaded with the Geographiclib CLI tools.

Would it make sense to set this to `GEOGRAPHICLIB_DATA="${PREFIX}/share/GeographicLib` in the build script? That way, you don't accidentally save the download data to your system, outside the Conda environment.

Another option would be to set it to something like `$XDG_DATA_HOME`, but that's also outside the control of the current Conda environment.

**Comment by cffk** [comment]
The rational for having the default `GEOGRAPHICLIB_DATA` fixed (independent of `CMAKE_INSTALL_PREFIX`), was that `GEOGRAPHICLIB_DATA` points to a directory several **LARGE** files which hardly ever change. So it makes sense in the Conda context, for example, that all environments which have some version of GeographicLib installed should use the same copy of these files.

I still think that this choice makes sense.  Of course, there are occasions when you need different behavior, e.g., you want to zip up a self-contained environment with GeographicLib and the associated data files.  However, in this case, you can have the activate script set the environment variable `GEOGRAPHICLIB_DATA` to override the hardwired setting.

P.S. I've not heard of `$XDG_DATA_HOME` until today.  I'm not sure it makes sense to adopt this convention.

**Comment by gwerbin** [comment]
@cffk thanks for the reply!

I understand, and I agree that's the right approach in general if these data files are big and infrequently changing. Other popular data science Python packages like NLTK, Scikit-Learn, and Seaborn all have similar data downloading functionality, and they take the same approach of storing data in a central location.

`GEOGRAPHICLIB_DATA` just sets the default download location, right? So users can change it as needed, e.g. setting it to their home directory on a system where they don't have root access.

That said, the XDG base directory specification is great! The [spec itself](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is decently readable and provides some rationale for the design. There's also this [tongue-in-cheek](https://xdgbasedirectoryspecification.com/) webpage that summarizes it.

**Comment by cffk** [comment]
Indeed, the user can set the environment variable `GEOGRAPHICLIB_DATA` to override the hard-wired setting.
